
services:
  # Görsel üretim servisi (SDXL-Turbo)
  imggen:
    build: ./services/image/imggen
    ports:
      - "${IMGGEN_PORT:-8001}:8000"
    environment:
      - MODEL_ID=${IMGGEN_MODEL:-stabilityai/sdxl-turbo}
      - MODEL_PATH=/app/models/sdxl-turbo
      - DEVICE=${DEVICE:-cuda}
    volumes:
      - ./models/sdxl-turbo:/app/models/sdxl-turbo
      - ./data/outputs/images:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # Görselden soru-cevap servisi (Qwen2.5VL-32B)
  # NOT: Ollama host'ta çalıştığı için host network kullan
  vqa:
    build: ./services/image/vqa
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${QWEN_VL_MODEL:-qwen2.5vl:32b}
    volumes:
      - ./data/uploads/images:/app/uploads
      - ./data/uploads/sessions:/app/sessions

  # Nesne tespiti servisi (Gemma3-27B)
  # NOT: Gemma3 Ollama üzerinden çalışır, GPU'ya gerek yok
  detect:
    build: ./services/image/detect
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - CONFIDENCE_THRESHOLD=${CONFIDENCE_THRESHOLD:-0.5}
    volumes:
      - ./data/uploads/images:/app/uploads
      - ./data/outputs/images:/app/outputs

  # PII Maskeleme servisi
  pii-masking:
    build: ./services/text/pii-masking
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
    volumes:
      - ./data/uploads/text:/app/uploads
      - ./data/outputs/text:/app/outputs

  # Quiz üretici servisi
  quiz-generator:
    build: ./services/text/quiz-generator
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - PORT=8006
    volumes:
      - ./data/uploads/text:/app/uploads
      - ./data/outputs/text:/app/outputs
      - ./data/quiz_sessions:/app/quiz_sessions

  # Şablona göre yeniden yazma servisi
  template-rewrite:
    build: ./services/text/template-rewrite
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - PORT=8005
    volumes:
      - ./data/uploads/text:/app/uploads
      - ./data/outputs/text:/app/outputs
      - ./services/text/template-rewrite/templates:/app/templates

  # Bilgi kartları servisi
  info-cards:
    build: ./services/text/info-cards
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - PORT=8008
    volumes:
      - ./data/uploads/text:/app/uploads
      - ./data/outputs/text:/app/outputs

  # Tablo işlemleri - Grafik üretici servisi
  chart-generator:
    build: ./services/table/chart-generator
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - PORT=8009
    volumes:
      - ./data/uploads/table:/app/uploads
      - ./data/outputs/table:/app/outputs

  # Tablo işlemleri - Tablo analiz servisi
  table-analyzer:
    build: ./services/table/table-analyzer
    network_mode: "host"
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL:-http://127.0.0.1:11434}
      - MODEL_NAME=${GEMMA_MODEL:-gemma3:27b}
      - PORT=8010
    volumes:
      - ./data/uploads/table:/app/uploads
      - ./data/outputs/table:/app/outputs

networks:
  default:
    name: ai-hub-network
