#!/bin/bash

echo "🚀 Template-Rewrite Servisi Test Komutları"
echo "=========================================="

echo "1. Servis sağlık kontrolü:"
echo "curl http://localhost:8005/health"
echo ""

echo "2. Mevcut şablonları listele:"
echo "curl http://localhost:8005/templates"
echo ""

echo "3. Gerekçe belgesi oluştur:"
echo "curl -X POST http://localhost:8005/generate-document \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d @test_template_rewrite.json"
echo ""
echo "4. Belgenet evrakı oluştur:"
echo "curl -X POST http://localhost:8005/generate-document \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d @test_belgenet.json"
echo ""
echo "5. Bilgi kartları oluştur:"
echo "curl -X POST http://localhost:8008/generate-cards \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d @test_info_cards.json"
echo ""

echo "6. Grafik üretici - JSON ile:"
echo "curl -X POST http://localhost:8009/generate-charts \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d @test_chart_generator.json"
echo ""

echo "7. Grafik üretici - CSV upload:"
echo "curl -X POST http://localhost:8009/upload-csv-and-generate \\"
echo "  -F \"file=@test_sales_data.csv\" \\"
echo "  -F \"max_charts=3\" \\"
echo "  -F \"output_format=png\""
echo ""

echo "8. Tablo analiz - JSON ile:"
echo "curl -X POST http://localhost:8010/analyze-table \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  -d @test_table_analyzer.json"
echo ""

echo "9. Tablo analiz - CSV upload:"
echo "curl -X POST http://localhost:8010/upload-csv-and-analyze \\"
echo "  -F \"file=@test_sales_data.csv\" \\"
echo "  -F \"language=turkish\""
echo ""

echo "10. Oluşturulan dosyayı indir:"
echo "curl http://localhost:8005/download/[filename]"
echo ""

echo "11. Servis logları:"
echo "sudo docker compose logs template-rewrite"
echo "sudo docker compose logs info-cards"
echo "sudo docker compose logs chart-generator"
echo "sudo docker compose logs table-analyzer"
echo ""

echo "12. Servis durumu:"
echo "sudo docker compose ps template-rewrite"
echo "sudo docker compose ps info-cards"
echo "sudo docker compose ps chart-generator"
echo "sudo docker compose ps table-analyzer"
